export const KEYS_DEFAULT_STATE = [
	[
		{ id: 1, key: "~", color: "", active: false },
		{ id: 2, key: "1", color: "", active: false },
		{ id: 3, key: "2", color: "", active: false },
		{ id: 4, key: "3", color: "", active: false },
		{ id: 5, key: "4", color: "", active: false },
		{ id: 6, key: "5", color: "", active: false },
		{ id: 7, key: "6", color: "", active: false },
		{ id: 8, key: "7", color: "", active: false },
		{ id: 9, key: "8", color: "", active: false },
		{ id: 10, key: "9", color: "", active: false },
		{ id: 11, key: "0", color: "", active: false },
		{ id: 12, key: "-", color: "", active: false },
		{ id: 13, key: "+", color: "", active: false },
		{ id: 14, key: "BACKSPACE", color: "", active: false },
	],
	[
		{ id: 15, key: "TAB", color: "", active: false },
		{ id: 16, key: "Q", color: "", active: false },
		{ id: 17, key: "W", color: "", active: false },
		{ id: 18, key: "E", color: "", active: false },
		{ id: 19, key: "R", color: "", active: false },
		{ id: 20, key: "T", color: "", active: false },
		{ id: 21, key: "Y", color: "", active: false },
		{ id: 22, key: "U", color: "", active: false },
		{ id: 23, key: "I", color: "", active: false },
		{ id: 24, key: "O", color: "", active: false },
		{ id: 25, key: "P", color: "", active: false },
		{ id: 26, key: "[", color: "", active: false },
		{ id: 27, key: "]", color: "", active: false },
		{ id: 28, key: "ENTER", color: "", active: false },
	],
	[
		{ id: 29, key: "CAPS", color: "", active: false },
		{ id: 30, key: "A", color: "", active: false },
		{ id: 31, key: "S", color: "", active: false },
		{ id: 32, key: "D", color: "", active: false },
		{ id: 33, key: "F", color: "", active: false },
		{ id: 34, key: "G", color: "", active: false },
		{ id: 35, key: "H", color: "", active: false },
		{ id: 36, key: "J", color: "", active: false },
		{ id: 37, key: "K", color: "", active: false },
		{ id: 38, key: "L", color: "", active: false },
		{ id: 39, key: ";", color: "", active: false },
		{ id: 40, key: '"', color: "", active: false },
		{ id: 41, key: "\\", color: "", active: false },
	],
	[
		{ id: 42, key: "SHIFT-L", color: "", active: false },
		{ id: 43, key: "Z", color: "", active: false },
		{ id: 44, key: "X", color: "", active: false },
		{ id: 45, key: "C", color: "", active: false },
		{ id: 46, key: "V", color: "", active: false },
		{ id: 47, key: "B", color: "", active: false },
		{ id: 48, key: "N", color: "", active: false },
		{ id: 49, key: "M", color: "", active: false },
		{ id: 50, key: "<", color: "", active: false },
		{ id: 51, key: ">", color: "", active: false },
		{ id: 52, key: "/", color: "", active: false },
		{ id: 53, key: "SHIFT-R", color: "", active: false },
	],
	[
		{ id: 54, key: "CTRL-L", color: "", active: false },
		{ id: 55, key: "WIN", color: "", active: false },
		{ id: 56, key: "ALT-L", color: "", active: false },
		{ id: 57, key: "SPACE", color: "", active: false },
		{ id: 58, key: "ALT-R", color: "", active: false },
		{ id: 59, key: "FN", color: "", active: false },
		{ id: 60, key: "DRUCK", color: "", active: false },
		{ id: 61, key: "CTRL-R", color: "", active: false },
	],
];
